global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'distributed-storage-coordinator'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 5s
    metrics_path: /metrics

  - job_name: 'distributed-storage-nodes'
    static_configs:
      - targets:
        - 'host.docker.internal:8081'
        - 'host.docker.internal:8082'
        - 'host.docker.internal:8083'
        - 'host.docker.internal:8084'
    scrape_interval: 5s
    metrics_path: /metrics