server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: distributed-storage
    static_configs:
      - targets:
          - localhost
        labels:
          job: distributed-storage
          __path__: /var/log/distributed-storage/**/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            caller: caller
      - labels:
          service:
          level:
      - timestamp:
          source: timestamp
          format: RFC3339 